language: go

go:
  - 1.12.x
  - 1.13.x

before_install:
  - go get -t -v ./...
  - go get github.com/mattn/goveralls

script:
  - $GOPATH/bin/goveralls -service=travis-ci
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
